test_that("predictCellCycle works properly", {
    ccgenes <- unique(unlist(readRDS(system.file("extdata", "CellCycleGenesets_Human_Whitfield2002.rds", package = "griph"))))
    set.seed(928374)
    M <- matrix(stats::rpois(n = 500*5, lambda = 2^stats::rnorm(500, 3)), ncol = 5)
    rownames(M) <- sample(ccgenes, size = 500)
    cc1 <- predictCellCycle(M, org = "human", granularity = "high")
    cc2 <- predictCellCycle(M, org = "human", granularity = "low")
    expect_error(predictCellCycle(M, org = "mouse"))
    expect_is(cc1, "factor")
    expect_equal(nlevels(cc1), 10)
    expect_equal(nlevels(cc2), 5)
    expect_length(cc1, 5)
    expect_equal(as.vector(table(cc1)), c(0,1,1,0,1,1,0,0,0,1))
    expect_equal(as.vector(table(cc2)), c(2,1,1,1,0))
})
