test_that("SC_cluster works properly", {
    M <- readRDS(system.file("extdata", "buettner_top10k.rds", package = "griph"))
    lab <- attr(M, "label")
    res1 <- SC_cluster(M, plotG = FALSE)
    # res2 <- SC_cluster(M, plotG = FALSE, use.par = TRUE, ncores = 4)
    expect_is(res1, "list")
    # expect_identical(res1$MEMB, res2$MEMB)
    # expect_identical(res1$DISTM, res2$DISTM)
    # expect_identical(res1$specp, res2$specp)
    expect_equal(griph:::classError(res1$MEMB, lab), 28/288)
})
