# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Hellinger distance between columns of a matrix.
#'
#' @description
#' \code{HellingerMat} returns a matrix of Hellinger distances between
#' the columns of the matrix passed as argument.
#'
#' @details
#' This function calculates the Hellinger distances between columns of the matrix
#' given as argument. It is implemented in C++ for efficiency. For an argument
#' matrix with r rows and c columns, the return value is an c-by-c matrix with
#' all pairwise distances.
#'
#' @param A Numeric matrix.
#'
#' @return A square matrix of dimensions \code{ncol(A})-by-\code{ncol(A)}.
#'
#' @examples
#' x <- matrix(1:12, nrow=3, ncol=4)
#' HellingerMat(x)
#'
HellingerMat <- function(A) {
    .Call('griph_HellingerMat', PACKAGE = 'griph', A)
}

#' @title Jensen-Shannon divergence between rows of a matrix.
#'
#' @description
#' \code{JSDmat} returns a matrix of Jensen-Shannon divergences between the rows
#' of the matrix passed as argument.
#'
#' @details
#' This function calculates the Jensen-Shannon divergences between row of the matrix
#' given as argument. It is implemented in C++ for efficiency. For an argument
#' matrix with r rows and c columns, the return value is an r-by-r matrix with
#' all pairwise distances, where only the upper-triangle of the matrix is filled.
#'
#' @param A Numeric matrix.
#'
#' @return A square matrix of dimensions \code{nrow(A})-by-\code{nrow(A)}.
#'
#' @examples
#' x <- matrix(1:12, nrow=3, ncol=4)
#' JSDmat(t(x))
#'
JSDmat <- function(A) {
    .Call('griph_JSDmat', PACKAGE = 'griph', A)
}

